from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent

DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
BASELINES_DIR = PROJECT_ROOT / "baselines"

IMT_AUDIT_RESULTS_DIR = RESULTS_DIR / "imt_audit"
BASELINE_RESULTS_DIR = RESULTS_DIR / "baselines"
EVAL_RESULTS_DIR = RESULTS_DIR / "eval"
FIGURES_DIR = RESULTS_DIR / "figures"

# ── Single-turn datasets: one directory per model, each holding one
# dataset_with_labels.json (prompt + responses + human-annotated ground truth).
# Every consumer (pipeline workflows, baseline runners) reads only the
# "prompt"/"responses" fields and never the "human_eval" field, so the same
# labeled file safely serves as both pipeline input and evaluation ground
# truth — there is no separate "no label" variant to keep in sync.
SINGLETURN_DIR = DATA_DIR / "singleturn"

ALL_MODEL_TARGETS = ["deepseek_r1", "gpt4o", "claude_sonnet46", "qwen25_7b"]
# The paper's primary single-turn dataset (DeepSeek-R1 generations); the other
# three targets extend human-annotated ground truth to additional models.
HUMAN_EVAL_TARGETS = ["gpt4o", "claude_sonnet46", "qwen25_7b"]


def model_dataset_path(target: str) -> Path:
    return SINGLETURN_DIR / target / "dataset_with_labels.json"


DEEPSEEK_DATASET = model_dataset_path("deepseek_r1")

# ── Multi-turn dataset (OpenDeception) ──────────────────────────────────────────
OPEN_DECEPTION_DIR = DATA_DIR / "open_deception"
OPEN_DECEPTION_C187_DIR = OPEN_DECEPTION_DIR / "OpenDeception-C187"
OPEN_DECEPTION_RAW_DIR = OPEN_DECEPTION_C187_DIR / "transcripts"
OPEN_DECEPTION_EXAMPLES = OPEN_DECEPTION_C187_DIR / "examples.py"
# Generated by `python scripts/parse_open_deception.py` from OPEN_DECEPTION_RAW_DIR;
# not checked in (it's a deterministic function of the raw transcripts above).
OPEN_DECEPTION_INPUT = OPEN_DECEPTION_DIR / "open_deception_gpt4o_en.json"

# ── Audit/eval output locations for the human-eval targets ─────────────────────
HUMAN_EVAL_AUDIT_RESULTS_DIR = RESULTS_DIR / "imt_audit_human_eval"
HUMAN_EVAL_EVAL_RESULTS_DIR = EVAL_RESULTS_DIR / "imt_human_eval"


def ensure_project_dirs() -> None:
    for path in (
        DATA_DIR,
        RESULTS_DIR,
        SCRIPTS_DIR,
        BASELINES_DIR,
        IMT_AUDIT_RESULTS_DIR,
        BASELINE_RESULTS_DIR,
        EVAL_RESULTS_DIR,
        FIGURES_DIR,
    ):
        path.mkdir(parents=True, exist_ok=True)
