from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent

DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
BASELINES_DIR = PROJECT_ROOT / "baselines"

IMT_AUDIT_RESULTS_DIR = RESULTS_DIR / "imt_audit"
BASELINE_RESULTS_DIR = RESULTS_DIR / "baselines"
EVAL_RESULTS_DIR = RESULTS_DIR / "eval"
FIGURES_DIR = RESULTS_DIR / "figures"

# ── Single-turn dataset (DeceptionBench-style scenarios) ───────────────────────
DEFAULT_DATASET_NO_EVAL = DATA_DIR / "deepseek_dataset_150_no_label.json"
DEFAULT_DATASET_HUMAN_EVAL = DATA_DIR / "deepseek_dataset_150_with_labels.json"

# ── Multi-turn dataset (OpenDeception) ──────────────────────────────────────────
OPEN_DECEPTION_DIR = DATA_DIR / "open_deception"
OPEN_DECEPTION_C187_DIR = OPEN_DECEPTION_DIR / "OpenDeception-C187"
OPEN_DECEPTION_RAW_DIR = OPEN_DECEPTION_C187_DIR / "data"
OPEN_DECEPTION_EXAMPLES = OPEN_DECEPTION_C187_DIR / "examples.py"
# Generated by `python scripts/parse_open_deception.py` from OPEN_DECEPTION_RAW_DIR;
# not checked in (it's a deterministic function of the raw transcripts above).
OPEN_DECEPTION_INPUT = OPEN_DECEPTION_DIR / "open_deception_gpt4o_en.json"

# ── Human-annotated ground truth for additional models ─────────────────────────
# (extends the paper's DeepSeek-R1-only set to GPT-4o, Claude Sonnet 4.6, Qwen2.5-7B)
HUMAN_EVAL_DIR = DATA_DIR / "human_eval"
HUMAN_EVAL_DATA_DIR = HUMAN_EVAL_DIR / "models"
HUMAN_EVAL_AUDIT_RESULTS_DIR = RESULTS_DIR / "imt_audit_human_eval"
HUMAN_EVAL_EVAL_RESULTS_DIR = EVAL_RESULTS_DIR / "imt_human_eval"

# Not used in this repo (no legacy data layout here); kept only because
# workflows/imt_audit_workflow.py falls back to it when the primary dataset
# path is missing.
LEGACY_DATA_DIR = DATA_DIR / "_legacy"


def resolve_data_file(primary: Path, legacy: Path) -> Path:
    if primary.exists():
        return primary
    return legacy


def ensure_project_dirs() -> None:
    for path in (
        DATA_DIR,
        RESULTS_DIR,
        SCRIPTS_DIR,
        BASELINES_DIR,
        IMT_AUDIT_RESULTS_DIR,
        BASELINE_RESULTS_DIR,
        EVAL_RESULTS_DIR,
        FIGURES_DIR,
    ):
        path.mkdir(parents=True, exist_ok=True)
